### ISSUE TITLE
3rd party references

### ISSUE THREAD

**Issue by mejje** [uglybugger/Add-BindingRedirect#1]
Correct me if I'm wrong, but this project doesn't resolve references from the NuGet packages itself, right?

For instance if you have a solution with only one project and add two NuGet packages that relies on different versions of a library, the binding is not added, right? I noticed you add all bindings now since 0969d4a, is this why you added it?

I'm looking for a solution to automate this as well, but the Add-BindingRedirect cmdlet looks dependent on Visual Studio DTE itself.

(e.g. new empty project with reference to Microsoft.AspNet.WebApi.Client and WebGrease causes a bindingredirect to 6.0.0 of Newtonsoft.Json)

**Comment by uglybugger** [comment]
You're pretty much correct; it doesn't look for references in the `package.config` at all. It goes hunting through every .csproj it finds and adds binding redirects for all of the assemblies for which it has multiple matches. That means that if a NuGet package itself has a mismatched dependency version, it previously wouldn't have been redirected.

Yes, 0969d4a was intended to address that. It means that there are more potentially-unnecessary redirects added, but it's much more reliable.

Does that help?

**Comment by mejje** [comment]
Yeah, I ended up doing a hacky automation solution in PowerShell instead :P.

```
Function global:add-binding-redirects-globally {
    $slns = dir -recurse *.sln

    $dte = New-Object -comobject "VisualStudio.DTE.14.0"
    $dte.MainWindow.Activate()
    sleep 5
    $dte.ExecuteCommand("View.PackageManagerConsole")
    sleep 5

    foreach($sln in $slns) {
        Write-Output $sln;
        nuget restore $sln -ConfigFile .\Utils\NuGet.Config

        $dte.Solution.Open($sln)
        sleep 5
        $dte.ExecuteCommand("View.PackageManagerConsole", "Get-Project -All | Add-BindingRedirect")
        sleep 15
    }

    $dte.Quit()
}
```
